# Generated by Django 4.2.1 on 2023-05-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Elec', 'Electronics'), ('Food', 'Food'), ('Fa', 'Fashion'), ('Gro', 'Grocery'), ('Spo', 'Sports'), ('Bo', 'Books'), ('Ent', 'Entertainmaint')], max_length=30)),
            ],
        ),
    ]
